parameters:

  # SERVICES
  by.resizer.class:           Bigyouth\BigyouthImageResizerBundle\Services\ImageResizeService

  # TWIG EXTENSIONS
  by.resizer.extension.class: Bigyouth\BigyouthImageResizerBundle\Twig\Extension\ImageResizeExtension

services:

  # SERVICES
  by.resizer:
    class: "%by.resizer.class%"
    arguments:  ["@liip_imagine.cache.manager", "@liip_imagine.data.manager", "@liip_imagine.filter.manager"]

  # TWIG EXTENSIONS
  by.resizer.extension:
    class: "%by.resizer.extension.class%"
    public: false
    arguments:  ["@service_container"]
    tags:
      - { name: twig.extension }